package com.youke.crm.ledger;
import java.util.List; import com.youke.crm.account.AccessPolicy; import com.youke.crm.common.NotFoundException; import com.youke.crm.order.SalesOrderRepository; import org.springframework.data.domain.Sort; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly=true) public class LedgerService {
 private final LedgerAccountRepository records; private final SalesOrderRepository orders; private final AccessPolicy policy;
 public LedgerService(LedgerAccountRepository r,SalesOrderRepository o,AccessPolicy p){records=r;orders=o;policy=p;}
 public List<LedgerResponse> list(Authentication a){policy.scopedOwner(a);return records.findAll(Sort.by(Sort.Direction.DESC,"id")).stream().filter(r->orders.findByOrderNo(r.getOrderNo()).map(o->policy.canAccessOwner(o.getOwner(),a)).orElse(false)).map(LedgerResponse::from).toList();}
 @Transactional public LedgerResponse create(LedgerRequest q,Authentication a){if(records.existsByOrderNo(q.orderNo()))throw new IllegalArgumentException("order already has ledger");var o=orders.findByOrderNo(q.orderNo()).orElseThrow(()->new NotFoundException("order not found"));policy.requireOwner(o.getOwner(),a);if(o.getPaidAmount().signum()<=0||q.ledgerAmount().compareTo(o.getPaidAmount())>0)throw new IllegalArgumentException("invalid ledger amount");var r=new LedgerAccount();r.setLedgerNo("FZ"+System.currentTimeMillis());r.setStoreName(q.storeName().trim());r.setSourceMerchant(q.storeName().trim());r.setFlowNo("LS"+System.currentTimeMillis());r.setOrderNo(o.getOrderNo());r.setOrderAmount(o.getAmount());r.setFeeAmount(q.ledgerAmount());r.setLedgerAmount(q.ledgerAmount());r.setBeneficiary(q.beneficiary().trim());r.setExecutionStatus("pending");r.setAllocatedAt(java.time.LocalDateTime.now());return LedgerResponse.from(records.save(r));}
 @Transactional public LedgerResponse execute(String id,Authentication a){var r=records.findByLedgerNo(id).orElseThrow(()->new NotFoundException("ledger not found"));var o=orders.findByOrderNo(r.getOrderNo()).orElseThrow(()->new NotFoundException("order not found"));policy.requireOwner(o.getOwner(),a);return LedgerResponse.from(r);}
}
